### ISSUE TITLE
Test data access

### ISSUE THREAD

**Issue by c2h5oh** [avct/uasurfer#18]
Can you share the `random sample of real UA strings collected across thousands of sources in US and EU mid-2016` mentioned in readme?

I wanted to add some bits things to uasurfer (expect pull requests soon), but I'd rather test it on my own first. I could get the list from our own logs, but I fear that the sample would not be representative.

**Comment by jacobpierce** [comment]
I'd go with your logs as anything newer is likely a more representative test, I do the same each time I make changes as to have recent UA strings

**Comment by c2h5oh** [comment]
The problem is our service users are not a representative sample of internet users in general - we have a lot of enterprise customers with employee laptops all locked in to a single OS/Browser organization-wide.

**Comment by jacobpierce** [comment]
My data represents 🇺🇸 🇬🇧  - to get new data I need to update my scripts that grep through logs. Can't commit on a date ATM but when I have them I'll share. For now the built-in tests have solid English-speaking country coverage.
