### ISSUE TITLE
Sometimes recognizes Safari as Opera

### ISSUE THREAD

**Issue by kingblade** [avct/uasurfer#35]
Hey there!
I've recently adopted your package into my project, and after running a lot of tests I've come to some User Agents where your package recognize them as opera while they are from safari:

UA:
`"Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) OPiOS/8.0.0.78129 Mobile/11D201 Safari/9537.53 XrRhbohyvvUWmRtipEat388XI4n5O7" `

UASURFER:
`&{Browser:{Name:BrowserOpera Version:{Major:8 Minor:0 Patch:0}} OS:{Platform:PlatformiPhone Name:OSiOS Version:{Major:7 Minor:1 Patch:1}} DeviceType:DevicePhone}`

UA2:
`"Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) OPiOS/16.0.8.121059 Mobile/14B100 Safari/9537.53"`

UASURFER2:
`&{Browser:{Name:BrowserOpera Version:{Major:16 Minor:0 Patch:8}} OS:{Platform:PlatformiPhone Name:OSiOS Version:{Major:10 Minor:1 Patch:1}} DeviceType:DevicePhone}`

Thank you for all the hard work (:

**Comment by ryanslade** [comment]
I think this is correct.

https://developers.whatismybrowser.com/useragents/parse/ also parses it as Opera
