### ISSUE TITLE
Remove prefix from parsed ua string

### ISSUE THREAD

**Issue by saifat29** [avct/uasurfer#39]
Following is the parsed output of an UA string. What is the need for prefixing type name to actual value, like in `BrowserName` isn't it better to have just `Chrome` and not `BrowserChrome`?

Current output-
```
{
    Browser {
        BrowserName: BrowserChrome,
        Version: {
            Major: 45,
            Minor: 0,
            Patch: 2454,
        },
    },
    OS {
        Platform: PlatformMac,
        Name: OSMacOSX,
        Version: {
            Major: 10,
            Minor: 10,
            Patch: 5,
        },
    },
    DeviceType: DeviceComputer,
}
```

 Desired output-
```
{
    Browser {
        BrowserName: Chrome,
        Version: {
            Major: 45,
            Minor: 0,
            Patch: 2454,
        },
    },
    OS {
        Platform: Mac,
        Name: MacOSX,
        Version: {
            Major: 10,
            Minor: 10,
            Patch: 5,
        },
    },
    DeviceType: Computer,
}
```

**Comment by ryanslade** [comment]
This is just a convention in Go which makes it easier to distinguish the types of values more easily and helps with autocompletion.

**Comment by djarbz** [comment]
Bump
I just found this library and it's really fast and I think will work well for my use.
However, I don't want/need it to include the prefix.
Perhaps, add a .String() method that will remove the prefix?

**Comment by ryanslade** [comment]
I don't want to alter the current `String()` method as it could break clients of the library.

However, I'm happy to add a `StringTrimPrefix()` method with will remove the prefix. Would that work for you?

**Comment by saifat29** [comment]
If it fulfills the purpose of removing the prefix when required then why not.
