### ISSUE TITLE
safari on webos

### ISSUE THREAD

**Issue by kayabe** [avct/uasurfer#43]
useragent: `Mozilla/5.0 (webOS/2.0.1; U; en-US) AppleWebKit/532.2 (KHTML, like Gecko) Version/1.0 Safari/532.2 Pre/1.2`

safari on webos shows BrowserUnknown due to:
`case strings.Contains(ua, "like gecko") && strings.Contains(ua, "mozilla/") && strings.Contains(ua, "safari/") && !strings.Contains(ua, "linux") && !strings.Contains(ua, "android") && !strings.Contains(ua, "browser/") && !strings.Contains(ua, "os/") && !strings.Contains(ua, "yabrowser/"):`

more exactly `!strings.Contains(ua, "os/")`
also fixed if replaced with `!(strings.Contains(ua, "os/") && !strings.Contains(ua, "webos/"))`

**Comment by ryanslade** [comment]
The browser isn't actually Safari. It uses WebKit under the hood, as do a lot of other browsers.

As there isn't any additional information we can't make a good guess as to what browser is actually being used.
